Traceback (most recent call last):
  File "main_imgreid.py", line 298, in <module>
    main(parser.parse_args())
  File "main_imgreid.py", line 137, in main
    args.combine_trainval, args.rerank)
  File "main_imgreid.py", line 77, in get_data
    cuhk03_labeled=True, cuhk03_classic_split=False,
  File "/mnt/linux/tzy/Relation-Aware-Global-Attention-Networks/reid/data_manager/__init__.py", line 17, in init_imgreid_dataset
    return __imgreid_factory[name](**kwargs)
  File "/mnt/linux/tzy/Relation-Aware-Global-Attention-Networks/reid/data_manager/cuhk03.py", line 62, in __init__
    self._check_before_run()
  File "/mnt/linux/tzy/Relation-Aware-Global-Attention-Networks/reid/data_manager/cuhk03.py", line 115, in _check_before_run
    raise RuntimeError("'{}' is not available".format(self.dataset_dir))
RuntimeError: '/YOUR_DATASET_PATH/cuhk03' is not available
